# Generated by Django 5.2.5 on 2025-08-21 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_por_kilo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kilos_disponibles', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('valencia', 'Valencia'), ('navel', 'Navel'), ('sanguina', 'Sanguina'), ('otra', 'Otra variedad')], max_length=20)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
