# Generated by Django 5.2.5 on 2025-09-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_venta_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_vendida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
